export default () => ({
  autoQuery: false,
  autoCreate: true,
  fields: [
    {
      label: '产线动态',
      name: 'proLineMove',
      type: 'string',
      required: true,
    },
    {
      label: '合格率',
      name: 'okPercent',
      type: 'number',
      step: 1,
      min: 0,
      required: true,
    },
    {
      name: 'ngPercent',
      label: '不合格率',
      type: 'number',
      required: true,
      step: 1,
      min: 0,
    },
    {
      name: 'completedPercent',
      label: '检验完成率',
      type: 'number',
      required: true,
      step: 1,
      min: 0,
    },
    // 检验单信息
    {
      label: '物料',
      name: 'itemCode1',
      type: 'string',
    },
    {
      label: '物料描述',
      name: 'itemDesc1',
      type: 'string',
    },
    {
      label: 'MO号',
      name: 'moNum1',
      type: 'string',
    },
    {
      label: '检验人员',
      name: 'attribute8',
      type: 'string',
    },
    {
      label: '检验单号',
      name: 'attribute9',
      type: 'string',
    },
    {
      label: '判定时间',
      name: 'attribute10',
      type: 'string',
    },
    // 当日产量
    {
      label: '当天产量',
      name: 'MONTH_PRODUCT_SUM_DAY',
      type: 'number',
      step: 0.1,
      min: 0,
      required: true,
    },
    {
      label: '新建订单',
      name: 'NEW_MO_SUM_DAY',
      type: 'number',
      step: 0.1,
      min: 0,
      required: true,
    },
    {
      label: '在制定单',
      name: 'RUNNING_MO_SUM_DAY',
      type: 'number',
      step: 0.1,
      min: 0,
      required: true,
    },
    {
      label: '完成订单',
      name: 'COMPLETED_MO_SUM_DAY',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    {
      label: '计划完成量',
      name: 'PLAN_PRODUCT_DAY',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    // 当周产量
    {
      label: '当周产量',
      name: 'MONTH_PRODUCT_SUM_WEEK',
      type: 'number',
      step: 0.1,
      min: 0,
      required: true,
    },
    {
      label: '新建订单',
      name: 'NEW_MO_SUM_WEEK',
      type: 'number',
      step: 0.1,
      min: 0,
      required: true,
    },
    {
      label: '在制定单',
      name: 'RUNNING_MO_SUM_WEEK',
      type: 'number',
      step: 0.1,
      min: 0,
      required: true,
    },
    {
      label: '完成订单',
      name: 'COMPLETED_MO_SUM_WEEK',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    {
      label: '计划完成量',
      name: 'PLAN_PRODUCT_WEEK',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    // 当月生产
    {
      label: '当月产量',
      name: 'MONTH_PRODUCT_SUM',
      type: 'number',
      step: 0.1,
      min: 0,
      required: true,
    },
    {
      label: '新建订单',
      name: 'NEW_MO_SUM',
      type: 'number',
      step: 0.1,
      min: 0,
      required: true,
    },
    {
      label: '在制定单',
      name: 'RUNNING_MO_SUM',
      type: 'number',
      step: 0.1,
      min: 0,
      required: true,
    },
    {
      label: '完成订单',
      name: 'COMPLETED_MO_SUM',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    {
      label: '计划完成量',
      name: 'PLAN_PRODUCT',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    // 产量统计
    {
      label: '第一天',
      name: 'COMPLETED_MO_SUM_1',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    {
      label: '第二天',
      name: 'COMPLETED_MO_SUM_2',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    {
      label: '第三天',
      name: 'COMPLETED_MO_SUM_3',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    {
      label: '第四天',
      name: 'COMPLETED_MO_SUM_4',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    {
      label: '第五天',
      name: 'COMPLETED_MO_SUM_5',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    {
      label: '第六天',
      name: 'COMPLETED_MO_SUM_6',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    {
      label: '第七天',
      name: 'COMPLETED_MO_SUM_7',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    // 生产概况
    {
      label: '物料',
      name: 'itemCode',
      type: 'string',
    },
    {
      label: '物料描述',
      name: 'itemDesc',
      type: 'string',
    },
    {
      label: 'MO号',
      name: 'moNum',
      type: 'string',
    },
    {
      label: '产线',
      name: 'prodLine',
      type: 'string',
    },
    {
      label: '订单数量',
      name: 'demandQty',
      type: 'string',
    },
    {
      label: '合格数量',
      name: 'okQty',
      type: 'string',
    },
    {
      label: '报废数量',
      name: 'scrappedQty',
      type: 'string',
    },
    {
      label: '计划开始',
      name: 'planStartDate',
      type: 'dateTime',
    },
    {
      label: '计划结束',
      name: 'planEndDate',
      type: 'dateTime',
    },
    // 安灯异常
    {
      label: '总异常',
      name: 'totalAbnormal',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    {
      label: '已触发',
      name: 'TRIGGERED_ANDON',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    {
      label: '已响应',
      name: 'RESPONSED_ANDON',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    {
      label: '已关闭',
      name: 'CLOSED_ANDON',
      type: 'number',
      required: true,
      step: 0.1,
      min: 0,
    },
    // 安灯信息
    {
      label: '安灯',
      name: 'andonCode',
      type: 'string',
    },
    {
      label: '安灯名称',
      name: 'andonName',
      type: 'string',
    },
    {
      label: '触发时间',
      name: 'triggeredTime',
      type: 'string',
    },
    {
      label: '关联资源',
      name: 'andonClassName',
      type: 'string',
    },
    {
      label: '所在位置',
      name: 'prodLineName',
      type: 'string',
    },
    {
      label: '安灯类型',
      name: 'andonRelTypeMeaning',
      type: 'string',
    },
    {
      label: '触发时长',
      name: 'triggeredDuration',
      type: 'number',
    },
  ],
});
